(() => {
  const priceNumber = value => Number(String(value).replace(/[^0-9]/g, '')) || 0;
  const won = value => `₩${value.toLocaleString('ko-KR')}`;
  const escapeHtml = value => String(value).replace(/[&<>'"]/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
  const itemsBox = document.getElementById('cart-items'), empty = document.getElementById('empty-cart');
  function render() {
    const items = SakarinCart.read();
    itemsBox.innerHTML = items.map((item,index)=>`<article class="grid grid-cols-[1fr_auto] gap-5 py-5 border-b border-line/30"><div><div class="font-mono text-[8px] text-primary tracking-widest">OBJECT ${String(index+1).padStart(2,'0')}</div><h3 class="font-serif text-2xl mt-1">${escapeHtml(item.name)}</h3><div class="text-sm text-muted mt-1">${escapeHtml(item.price)}</div></div><div class="flex items-center gap-3"><button class="qty w-8 h-8 bg-surface-low" data-index="${index}" data-delta="-1" aria-label="수량 감소">−</button><span class="font-mono text-sm min-w-4 text-center">${item.quantity}</span><button class="qty w-8 h-8 bg-surface-low" data-index="${index}" data-delta="1" aria-label="수량 증가">+</button><button class="remove ml-2 text-muted" data-index="${index}" aria-label="삭제"><span class="material-symbols-outlined text-lg">close</span></button></div></article>`).join('');
    empty.classList.toggle('hidden',items.length>0); itemsBox.classList.toggle('hidden',!items.length);
    const count=items.reduce((s,i)=>s+i.quantity,0), total=items.reduce((s,i)=>s+priceNumber(i.price)*i.quantity,0);
    document.getElementById('summary-count').textContent=count; document.getElementById('summary-total').textContent=won(total); document.getElementById('open-order').disabled=!items.length;
  }
  document.addEventListener('click',e=>{const q=e.target.closest('.qty'),r=e.target.closest('.remove');if(!q&&!r)return;const items=SakarinCart.read(),index=Number((q||r).dataset.index);if(r)items.splice(index,1);else{items[index].quantity+=Number(q.dataset.delta);if(items[index].quantity<1)items.splice(index,1);if(items[index]?.quantity>9)items[index].quantity=9}SakarinCart.write(items);render()});
  document.getElementById('clear-cart').addEventListener('click',()=>{SakarinCart.clear();render()});
  const modal=document.getElementById('order-modal');document.getElementById('open-order').addEventListener('click',()=>{modal.classList.replace('hidden','flex');document.body.style.overflow='hidden'});modal.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',()=>{modal.classList.replace('flex','hidden');document.body.style.overflow=''}));
  document.getElementById('order-form').addEventListener('submit',async e=>{e.preventDefault();const form=e.currentTarget,button=form.querySelector('[type=submit]'),status=document.getElementById('order-status'),items=SakarinCart.read();if(!items.length)return;button.disabled=true;status.className='block p-3 text-sm bg-surface-container text-muted';status.textContent='일괄 신청을 전송하고 있습니다.';const data=Object.fromEntries(new FormData(form));data.item=items.map(i=>`${i.name} × ${i.quantity}`).join(' / ');data.price=won(items.reduce((s,i)=>s+priceNumber(i.price)*i.quantity,0));data.quantity=String(items.reduce((s,i)=>s+i.quantity,0));data.option='일괄 주문';try{const response=await fetch('/api/reservations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}),result=await response.json().catch(()=>({}));if(!response.ok)throw new Error(result.message||'전송에 실패했습니다.');SakarinCart.clear();render();status.className='block p-3 text-sm bg-primary text-surface';status.textContent='일괄 신청이 담당자에게 발송되었습니다.';form.reset();setTimeout(()=>{modal.classList.replace('flex','hidden');document.body.style.overflow=''},1800)}catch(error){status.className='block p-3 text-sm bg-red-950 text-red-100';status.textContent=error.message==='Failed to fetch'?'메일 서버에 연결할 수 없습니다.':error.message}finally{button.disabled=false}});
  window.addEventListener('cartchange',render);render();
})();
